### ISSUE TITLE
Make galaxy-docker-ansible ready for an official release.

### ISSUE THREAD

**Issue by rhpvorderman** [lumc-sasc/galaxy-docker-ansible#28]
- [x]  Move documentation to read the docs or other readable platform.  (#27) 
- [x] Make sure developer documentation for all roles is up to date with a clear explanation of why some design choices were made. (#61) 
- [x] Make sure user guides are up to date and clear.
- [x] Set up continuous integration tests. (#56) 
- [x] decide on a version number for the release. (#28)
- [x] Update to latest version of ansible and fix all issues that prevented upgrading from 2.3.0.0 (#59)
- [x] Add versioning for dependencies. (#29 #30)
- [x] Change license to something more general. (#63)
- [x] Change name to something more palatable. (#66) 
- [x] Get logo. (#68)
- [x] Document release process changelog etc. (#70)

**Comment by rhpvorderman** [comment]
http://semver.org/

Since this is being used in production the version number shall be 1.0.0

**Comment by rhpvorderman** [comment]
Release 1.0.0 is out there #71
